board_project/board/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.advertisement_list, name='advertisement_list'),
    path('stat/', views.user_stat_list, name='user_stat_list'),
    path('settings/', views.user_settings, name='user_settings'),
    path('<int:pk>/', views.advertisement_list, name='advertisement_list'),
    path('advertisement/<int:pk>/', views.advertisement_detail, name='advertisement_detail'),
    path('edit/<int:pk>/', views.edit_advertisement, name='edit_advertisement'),
    path('edit_comment/<int:pk>/', views.edit_comment, name='edit_comment'),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('image_generation/<int:pk>/', views.image_generation, name='image_generation'),
    path('del/<int:pk>/', views.del_advertisement, name='del_advertisement'),
    path('add/', views.add_advertisement, name='add_advertisement'),
    path('add_comment/<int:pk>/', views.add_comment, name='add_comment'),
    path('add_image/<int:pk>/', views.add_image, name='add_image'),
    path('like/<int:pk>/<int:tp>/', views.like_dislike, name='like_dislike'),
]

board_project/board_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from board import views as board_views

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('board/', include('board.urls', namespace='board')),
    path('accounts/logout/', board_views.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', board_views.home, name='home'),
    path('signup/', board_views.signup, name='signup'),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

board_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Доска объявлений{% endblock %}</title>
    {% if user_pref.theme != 'dark' %}
      <link rel="stylesheet" type="text/css" href='{% static "board_project/style-day.css" %}'>
    {% else %}
      <link rel="stylesheet" type="text/css" href='{% static "board_project/style-night.css" %}'>
    {% endif %}
    <link rel="icon" href="{% static 'favicon3.ico' %}" />
    <script src="{% static 'reload.js' %}"></script>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'home' %}">Домой</a>
        <a href="{% url 'board:advertisement_list' %}">Доска объявлений</a>
        {% if user.is_authenticated %}
            {% if user.is_superuser %}
              <a href="{% url 'board:user_stat_list' %}">Статистика</a>
            {% endif %}
            <a href="{% url 'board:user_settings' %}">Настройки</a>
            <a href="{% url 'logout' %}">Выход (<span class="small_font">{{user}}</span>)</a>
            <a href="?day=theme" title="Светлая/темная тема">
                {% if user_pref.theme != 'dark' %}
                  <img src="{% static 'board_project/day.png' %}" width="34">
                {% else %}
                  <img src="{% static 'board_project/night.png' %}" width="34">
                {% endif %}
            </a>
        {% else %}
            <a href="{% url 'login' %}">Вход</a>
            <a href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </div>

    {% block content %}
    {% endblock %}

<br>  <hr>
    © HIT (Home Information Technology)
    <br> Пишите нам на почту: ✉<a href="mailto:mail@mail.ru"> mail@mail.ru </a>
    <br>  <br>

</body>
</html>

board_project/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% block title %}
    Главная страница
{% endblock %}
{% block content %}

    <h1>Добро пожаловать на наш сайт!</h1>
    <h2 class="align_left"><a href="/board/">Перейти к объявлениям</a></h2>
{% endblock %}