board_project/board/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.advertisement_list, name='advertisement_list'),
    path('stat/', views.user_stat_list, name='user_stat_list'),
    path('settings/', views.user_settings, name='user_settings'),
    path('<int:pk>/', views.advertisement_list, name='advertisement_list'),
    path('advertisement/<int:pk>/', views.advertisement_detail, name='advertisement_detail'),
    path('edit/<int:pk>/', views.edit_advertisement, name='edit_advertisement'),
    path('edit_comment/<int:pk>/', views.edit_comment, name='edit_comment'),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('image_generation/<int:pk>/', views.image_generation, name='image_generation'),
    path('del/<int:pk>/', views.del_advertisement, name='del_advertisement'),
    path('add/', views.add_advertisement, name='add_advertisement'),
    path('add_comment/<int:pk>/', views.add_comment, name='add_comment'),
    path('add_image/<int:pk>/', views.add_image, name='add_image'),
    path('like/<int:pk>/<int:tp>/', views.like_dislike, name='like_dislike'),
]

board_project/board_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from board import views as board_views

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('board/', include('board.urls', namespace='board')),
    path('accounts/logout/', board_views.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', board_views.home, name='home'),
    path('signup/', board_views.signup, name='signup'),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

board_project/board/forms.py
from django import forms
from django.utils.safestring import mark_safe

from .models import Advertisement, Image, Comment, Preferences
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AdvertisementForm(forms.ModelForm):
    """
    Форма для объявлений
    """
    title = forms.CharField(label='Заголовок объявления:', max_length=200)
    content = forms.CharField(label='Текст объявления:', widget=forms.Textarea, empty_value='')
    image = forms.ImageField(label='Изображение:', help_text='Загрузите картинку при необходимости.', required=False)

    class Meta:
        model = Advertisement
        fields = ['title', 'content', 'image']


class CommentForm(forms.ModelForm):
    """
    Форма для комментариев
    """
    content = forms.CharField(label='Текст комментария:', widget=forms.Textarea, empty_value='')

    class Meta:
        model = Comment
        fields = ['content']


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class ImageForm(forms.ModelForm):
    """
    Форма для загрузки картинок 2
    """
    photo = MultipleFileField(label='Выберите файлы:', required=False)

    class Meta:
        model = Image
        fields = ['photo', ]


class SignUpForm(UserCreationForm):
    """
    Форма для регистрации пользователей
    """
    username = forms.CharField(label='Ник пользователя:')
    first_name = forms.CharField(label='Имя пользователя (не обязательно):', required=False)
    password1 = forms.CharField(label='Введите пароль:', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль:', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'password1', 'password2',)


class PreferencesForm(forms.ModelForm):
    """
    Форма для предпочтений пользователя
    """
    # user = forms.CharField(label='Ник пользователя:')
    theme = forms.CharField(label='Тема (светлая/темная):', widget=forms.Select(choices=Preferences.themes))
    page_num = forms.IntegerField(label='Количество объявлений на страницу:')

    class Meta:
        model = Preferences
        fields = ['theme', 'page_num']

board_project/board/views.py
import logging
import os
import shutil
import time
from datetime import datetime
# from multiprocessing import Process
from threading import Thread

from django.core.paginator import Paginator
from django.conf import settings
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponseRedirect, HttpResponse
from .models import Advertisement, Image, Comment, Like, UserStat, Preferences
from .forms import AdvertisementForm, CommentForm, ImageForm, PreferencesForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib.auth import login
from .utilite import like_read, like_set, kandinsky_query, read_pade_count


def logout_view(request: HttpRequest) -> HttpResponseRedirect:
    """
    Представление - Выход из системы (logout)
    :param request: HttpRequest - запрос пользователя
    :return: HttpResponseRedirect - перенаправление на домашнюю страницу
    """
    logout(request)
    return redirect('login')


def signup(request: HttpRequest):
    """
    Представление - Регистрация пользователя
    :param request: HttpRequest - запрос пользователя
    :return: После регистрации перенаправление на страницу с объявлениями
    """
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            logging.info(f'Создан пользователь: {user}')
            login(request, user)
            return redirect('/board')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def home(request: HttpRequest):
    """
    Представление - Регистрация пользователя.
    :param request: HttpRequest - запрос пользователя.
    :return: После регистрации перенаправление на страницу с объявлениями.
    """
    return render(request, 'home.html')


def user_stat_list(request: HttpRequest):
    """
    Представление - Просмотр статистики по пользователям.
    :param request: HttpRequest - запрос пользователя.
    :return: Остаемся на странице.
    """
    user_stat = UserStat.objects.all()
    return render(request, 'board/user_statistic_list.html', {'user_stat': user_stat})


def user_settings(request: HttpRequest):
    """
    Изменить пользовательские настройки.
    :param request: HttpRequest - запрос пользователя.
    :return: Остаемся на странице.
    """
    user_stat = UserStat.objects.all()
    try:
        pref = Preferences.objects.get(user=request.user)
    except BaseException as er:
        logging.error(f'user_settings: {er}')
        Preferences.objects.create(user=request.user)
        pref = Preferences.objects.get(user=request.user)
    if request.method == "POST":
        form = PreferencesForm(request.POST, request.FILES, instance=pref)
        if form.is_valid():
            user_sett = form.save(commit=False)
            user_sett.user = request.user
            user_sett.save()
            return redirect('board:user_settings')
    else:
        form = PreferencesForm(instance=pref)
    return render(request, 'board/user_settings.html',
                  {'user_stat': user_stat, 'form': form})


def advertisement_list(request: HttpRequest, pk: int | None = None):
    """
    Представление - Просмотр списка объявлений.
    :param request: HttpRequest - запрос пользователя.
    :param pk: id объявления.
    :return: Остаемся на странице.
    """
    context = {}
    if pk:
        advertisements = Advertisement.objects.filter(author=pk).order_by('-id')
        user_stat_ = UserStat.objects.filter(user=pk)
        context = {'user_show': User.objects.get(id=pk)}
        if user_stat_:
            context['user_stat'] = user_stat_.first()
    else:
        advertisements = Advertisement.objects.all().order_by('-id')
    page_count = read_pade_count(request)
    paginator = Paginator(advertisements, page_count)
    page_num = request.GET.get('page')
    page_obj = paginator.get_page(page_num)
    images = []
    for adv in range(len(page_obj)):
        images.append(Image.objects.filter(advertisement=page_obj[adv].id))
    context = {**context, 'advertisements': zip(page_obj, images), 'advertisements_feeds': page_obj}
    return render(request, 'board/advertisement_list.html', context)


def advertisement_detail(request: HttpRequest, pk: int):
    """
    Представление - Просмотр выбранного объявления.
    :param request: HttpRequest - запрос пользователя.
    :param pk: id объявления.
    :return: В случае нажатия кнопки Редактировать - переходим на страницу редактирования объявления.
    """
    advertisement = Advertisement.objects.get(pk=pk)
    images = Image.objects.filter(advertisement=advertisement.id)
    comments = Comment.objects.filter(advertisement=advertisement.id)
    context = like_read(request, pk)
    if advertisement.author == request.user or request.user.is_superuser:
        context['reload'] = '<div id="reload"></div>'
    return render(request, 'board/advertisement_detail.html',
                  {'advertisement': advertisement,
                   'images': images,
                   'comments': comments,
                   **context})


@login_required
def add_advertisement(request: HttpRequest):
    """
    Представление - Добавить новое объявление.
    :param request: HttpRequest - запрос пользователя.
    :return: После добавления объявления, возвращаемся к списку объявлений.
    """
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.author = request.user
            advertisement.save()
            return redirect('board:advertisement_list')
    else:
        form = AdvertisementForm()
    return render(request, 'board/add_advertisement.html', {'form': form})


@login_required
def add_comment(request: HttpRequest, pk: int):
    """
    Представление - Добавить новый комментарий.
    :param request: HttpRequest - запрос пользователя.
    :param pk: id объявления.
    :return: После добавления комментария, возвращаемся к деталям объявления.
    """
    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.advertisement = Advertisement.objects.get(id=pk)
            comment.save()
            return redirect('board:advertisement_detail', pk=pk)
    else:
        form = CommentForm()
    return render(request, 'board/add_comment.html', {'form': form})


@login_required
def add_image(request: HttpRequest, pk: int):
    """
    Представление - Добавить новые картинки.
    :param request: HttpRequest - запрос пользователя.
    :param pk: id объявления.
    :return: После добавления картинок, возвращаемся к редактированию объявления.
    """
    advertisement = Advertisement.objects.get(id=pk)
    if request.method == "POST":
        uploaded_images = request.FILES.getlist('photo')
        for image in uploaded_images:
            Image.objects.create(advertisement=advertisement, user=request.user, image=image)
        return redirect('board:edit_advertisement', pk=pk)
    else:
        form = ImageForm()
    return render(request, 'board/add_image.html',
                  {'form': form, 'advertisement': advertisement})


@login_required
def edit_advertisement(request: HttpRequest, pk):
    """
    Представление - Редактирование выбранного объявления. Редактировать можно только
    свои объявления или суперпользователю можно редактировать все.
    :param request: HttpRequest - запрос пользователя.
    :param pk: id объявления.
    :return: После редактирования возвращаемся на страницу просмотра деталей выбранного объявления.
    """
    advertisement = Advertisement.objects.get(pk=pk)
    images = Image.objects.filter(advertisement=advertisement)
    if request.user != advertisement.author and not request.user.is_superuser:
        return render(request, 'board/advertisement_detail.html',
                      {'advertisement': advertisement, 'error': 'Вы не можете редактировать чужие объявления!'})
    if request.method == "POST" and request.POST.get('add_adv'):
        form = AdvertisementForm(request.POST, request.FILES, instance=advertisement)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.save()
            return redirect('board:advertisement_detail', pk=pk)
    elif request.method == "POST" and request.POST.get('image_del'):
        for img in images:
            image = request.POST.get(f'i{img.id}')
            if image:
                Image.objects.get(id=img.id).delete()
        form = AdvertisementForm(instance=advertisement)
        images = Image.objects.filter(advertisement=advertisement)
    else:
        form = AdvertisementForm(instance=advertisement)
    return render(request, 'board/add_advertisement.html',
                  {'form': form,
                   'title2': 'Редактировать объявление',
                   'advertisement': advertisement,
                   'images': images})

@login_required
def edit_comment(request: HttpRequest, pk):
    """
    Представление - Редактирование выбранного комментария. Редактировать можно только
    свои комментарии или суперпользователю можно редактировать все.
    :param request: HttpRequest - запрос пользователя.
    :param pk: id комментария.
    :return: После редактирования возвращаемся на ту же страницу.
    """
    comment = Comment.objects.get(pk=pk)
    # images = Image.objects.filter(advertisement=advertisement)
    if request.user != comment.author and not request.user.is_superuser:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES, instance=comment)

board_project/board/templates/board/add_advertisement.html
{% extends 'base.html' %}

{% block content %}
  <h2>
    {% if title2 %}
      {{ title2 }}
    {% else %}
      Добавить объявление
    {% endif %}
  </h2>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" name="add_adv" value="{{advertisement.pk}}">Готово!</button>
  </form>

<hr>

    <h2>Дополнительные картинки</h2>
  {% if title2 %}

    <a href="{% url 'board:add_image' pk=advertisement.pk %}"><button>Добавить картинки</button></a>
    <br> <br>
  {% endif %}

    {% if images %}
      <form method="post" id="myForm">
        {% csrf_token %}
        <nav>
        {% for itm in images %}
        <div class="container inline-block">
          <input type="checkbox" id="chb" name="i{{ itm.id }}" value="i{{ itm.id }}">
          <label for="chb">
            <a class="a_img" href="{{ itm.image.url }}" target="_blank">
              <img src="{{ itm.image.url }}"
                   title="{{ itm.url }} &#10Автор: {{ itm.user }}"
                   style="width: 300px; height: 300px;">
            </a>
          </label>

        </div>
        {% endfor %}
        </nav>
        <p class="align_left">
          <button onclick="return confirm('Удалить выбранные картинки?');" type="submit" name="image_del" value="checked">
            Удалить выбранные
          </button>
        </p>
      </form>
  {% endif %}
{% endblock %}

board_project/board/templates/board/add_comment.html
{% extends 'base.html' %}

{% block content %}
  <h2>
    {% if title2 %}
      {{ title2 }}
    {% else %}
      Добавить комментарий к объявлению
    {% endif %}
  </h2>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <hr>
    <button type="submit" name="add_adv" value="{{advertisement.pk}}">Готово!</button>
  </form>
{% endblock %}

board_project/board/templates/board/add_image.html
{% extends 'base.html' %}

{% block content %}
  <h2>
    Добавить изображение к объявлению:
  </h2>
<h3 class="big_font">{{ advertisement.title }}</h3>
<hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <hr>
    <button type="submit" name="add_adv" value="{{advertisement.pk}}">Готово!</button>
  </form>
{% endblock %}

board_project/board/templates/board/advertisement_detail.html
{% extends 'base.html' %}

{% block content %}
{{ reload|safe }}

<h1>{{ advertisement.title }}</h1>
<h3>Автор:
    <a href="{% url 'board:advertisement_list' pk=advertisement.author.id %}">
        {{ advertisement.author.username }}
    </a> &ensp;&ensp;&ensp;&ensp; <span  class="date_font"> {{ advertisement.created_at }} </span></h3>
<pre>{{ advertisement.content }}</pre>
{% if advertisement.image %}
<a class="a_img" href="{{ advertisement.image.url }}" target="_blank">
  <img src="{{ advertisement.image.url }}" style="height: 300px;">
</a>
{% endif %}
{% if images %}
  {% for i in images %}
    <a class="a_img" href="{{ i.image.url }}" target="_blank">
      <img src="{{ i.image.url }}" style="height: 300px;">
    </a>
  {% endfor %}
{% endif %}
<br>

<a class="a_img" href="{% url 'board:like_dislike' pk=advertisement.pk tp=1 %}">
  {% if like %}
    <img src="/static/board_project/like_on.png" width="40">
  {% else %}
    <img src="/static/board_project/like.png" width="40">
  {% endif %}
</a>
{{ advertisement.like_count }} &ensp;&ensp;
<a class="a_img" href="{% url 'board:like_dislike' pk=advertisement.pk tp=0 %}">
  {% if dislike %}
    <img src="/static/board_project/dislike_on.png" width="40">
  {% else %}
    <img src="/static/board_project/dislike.png" width="40">
  {% endif %}
</a>
{{ advertisement.dislike_count }}
<br>  <br>

{% if advertisement.author == user or user.is_superuser %}
<table class="no_border">
  <tr class="no_border">
      <th class="no_border">
      <form method="post" action="{% url 'board:edit_advertisement' pk=advertisement.pk %}">
        {% csrf_token %}
        <button type="submit" name="edit_adv" value="{{advertisement.pk}}">
            Редактировать
        </button>
      </form>
      </th>
      <th class="no_border">
      <form method="post" action="{% url 'board:del_advertisement' pk=advertisement.pk %}">
        {% csrf_token %}
        <button onclick="return confirm('Вы уверены, что хотите удалить это объявление?');"
                type="submit" name="del_adv" value="{{advertisement.pk}}">
            Удалить
        </button>
      </form>
      </th>
      <th class="no_border">
      <form method="post" action="{% url 'board:image_generation' pk=advertisement.pk %}">
        {% csrf_token %}
        <button onclick="return confirm('Вы уверены, что хотите сгенерировать изображение по запросу: {{ advertisement.title }} {{ advertisement.content }}?');"
                type="submit" name="gen_image" value="{{advertisement.pk}}">
            Сгенерировать картинку
        </button>
      </form>
      </th>
  </tr>
</table>
{% endif %}

{% if error %}
    <p class="red-text">{{ error }}</p>
{% endif %}
<br> <hr>
<h2>Комментарии:</h2>
{% if user.is_authenticated %}
    <a href="{% url 'board:add_comment' pk=advertisement.pk %}"><button>Добавить комментарий</button></a>
{% endif %}
 <br> <br>
{% if comments %}
    <table>
      <thead>
        <tr>
          <th>Содержание комментария</th>
          <th>Автор</th>
        </tr>
      </thead>
      {% for comment in comments %}
        <tr class="align_left">
          <th>
            <div class="date_font small_font">{{ comment.created_at }}</div>
            <pre class="normal_font">{{ comment.content }}</pre>
            {% if comment.author == user or user.is_superuser %}
              <div class="date_font small_font">
                <a href="{% url 'board:edit_comment' pk=comment.id %}">
                    Редактировать
                </a> &ensp;&ensp;
                <a href="{% url 'board:delete_comment' pk=comment.id %}"
                   onclick="return confirm('Вы уверены, что хотите удалить комментарий');">
                    Удалить
                </a>
              </div>
            {% endif %}
          </th>
          <th>
            <a href="{% url 'board:advertisement_list' pk=comment.author.id %}">{{ comment.author }}</a>
          </th>
        </tr>
      {% endfor %}
    </table>
{% endif %}

{% endblock %}

board_project/board/templates/board/advertisement_list.html
{% extends 'base.html' %}

{% block content %}
<div id="reload"></div>
<h1>Объявления</h1>
{% if user_show %} <h2>Все объявления пользователя: {{ user_show }} ({{ user_stat.advertisement_count }})</h2>
{% endif %}
{% if user.is_authenticated %}
    <a href="{% url 'board:add_advertisement' %}"><button>Добавить объявление</button></a>
    <br> <br>
{% endif %}
{% include 'board/paginator.html' %}
<table>
  <thead>
    <tr>
      <th>Объявления</th>
      <th>Фото</th>
      <th>Автор</th>
    </tr>
  </thead>
  {% for advertisement, images in advertisements %}
    <tr class="align_left">
      <th>
        <div class="date_font small_font">{{ advertisement.created_at }}</div>
        <a href="{% url 'board:advertisement_detail' pk=advertisement.pk %}">{{ advertisement.title }}</a>
        <div class="small_font">{{ advertisement.content|truncatechars:50 }}</div>
      </th>
      <th>
        {% if advertisement.image %}
          <a class="a_img" href="{{ advertisement.image.url }}" target="_blank">
            <img src="{{ advertisement.image.url }}" style="height: 30px;">
          </a>
        {% endif %}
        {% if images %}
          {% for img in images %}
            <a class="a_img" href="{{ img.image.url }}" target="_blank">
              <img src="{{ img.image.url }}" style="height: 30px;">
            </a>
          {% endfor %}
        {% endif %}
      </th>
      <th>
        <a href="{% url 'board:advertisement_list' pk=advertisement.author.id %}">
          {{ advertisement.author.username }}
        </a>
      </th>
    </tr>
  {% endfor %}
</table>
{% include 'board/paginator.html' %}

{% endblock %}

board_project/board/templates/board/paginator.html
<form method="get" action="{% url 'board:advertisement_list' %}" id="paginator">
<nav aria-label="Панель навигации">
  <ul>
    {% if advertisements_feeds.has_other_pages %}
      {% if advertisements_feeds.has_previous %}
        <li class="inline-block">
          <a href="?page={{ advertisements_feeds.previous_page_number }}" aria-label="Предыдущая страница">
            <span class="padding_font"> << </span>
          </a>
        </li>
      {% else %}
        <li class="inline-block"><span  class="padding_font"> << </span></li>
      {% endif %}

      {% for i in advertisements_feeds.paginator.page_range %}
        {% if advertisements_feeds.number == i %}
          <li class="inline-block">
            <span class="big_font padding_font"><b>{{ i }}</b></span>
          </li>
        {% else %}
          <li class="inline-block">
            <a href="?page={{ i }}">
              <span class="padding_font">{{ i }}</span>
            </a>
          </li>
        {% endif %}
      {% endfor %}

      {% if advertisements_feeds.has_next %}
        <li class="inline-block">
          <a href="?page={{ advertisements_feeds.next_page_number }}" aria-label="Следующая страница">
            <span class="padding_font"> >> </span>
          </a>
        </li>
      {% else %}
        <li class="inline-block"><span class="padding_font"> >> </span></li>
      {% endif %}
    {% if user.is_authenticated %}
      <b class="padding_font inline-block">|</b>
    {% endif %}
    {% endif %}
    {% if user.is_authenticated %}
    <span class="padding_font inline-block">Объявлений:</span>
      <select id="cnt" name="cnt"
              onchange="document.getElementById('paginator').submit();">
        <option value="0"></option>
        <option value="3">3</option>
        <option value="5">5</option>
        <option value="10">10</option>
        <option value="30">30</option>
        <option value="90">90</option>
        <option value="150">150</option>
      </select>
    {% endif %}
  </ul>
</nav>
</form>

board_project/board/templates/board/user_settings.html
{% extends 'base.html' %}

{% block content %}
  <h2>
    Пользовательские настройки
  </h2>
<a href="{% url 'password_change' %}">Сменить пароль</a> <br>
<a href="{% url 'password_reset' %}">Сбросить пароль</a>
<hr>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <hr>
    <button type="submit">Готово!</button>
  </form>
{% endblock %}

board_project/board/templates/board/user_statistic_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Статистика по пользователям</h1>
<table>
  <thead>
    <tr>
      <th>Пользователь</th>
      <th>Количество сообщений</th>
      <th>Количество комментариев</th>
      <th>Количество лайков</th>
      <th>Количество дизлайков</th>
    </tr>
  </thead>
  {% for user in user_stat %}
    <tr class="align_left">
      <th>
        <a href="{% url 'board:advertisement_list' pk=user.user.id %}">
          {{ user.user.username }}
        </a>
      </th>
      <th>
        {{ user.advertisement_count }}
      </th>
      <th>
        {{ user.comment_count }}
      </th>
      <th>
        {{ user.like_count }}
      </th>
      <th>
        {{ user.dislike_count }}
      </th>
    </tr>
  {% endfor %}
</table>

{% endblock %}